version: '3'
services:
  flask:
    build: .
    # command: gunicorn -w 4 -b 0.0.0.0:5000 hello:app --reload
    # it was for 4 workers
    command: gunicorn -b 0.0.0.0:5000 hello:app --reload
    # command: flask run --host=0.0.0.0 (not for production)
    environment:
      - FLASK_APP=hello.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - ./:/root